### ISSUE TITLE
<去他妈的 CSDN！全网屏蔽教程> 

### ISSUE THREAD

**Issue by 196961550** [faithleysath/faithleysath.github.io#1]
看了你的文章 <去他妈的 CSDN！全网屏蔽教程> f
本想回复你 但是你的页面丢失 无法登录评论
我还以为就我一个人讨厌csdn呢 原来大家都一样
这个csdn是真恶心 以前我记得很早很早以前
csdn就是一个小破站 靠分享软件链接 类似于软件下载站点
后来转型成了一个代码分享站点
到现在 满天飞的 搬运赚钱站点 
各种公共资源 搬运在服务器里 然后收费
让人感觉恶心

**Comment by faithleysath** [comment]
感谢阅读！是的，csdn干的骚操作层出不穷，比如之前的gitcode搬运github仓库也有csdn的参与，它们先是把仓库搬运过来，再在csdn上生成对应的文章引用gitcode的仓库。真的是无所不用其极。希望文章中的方法能对您起到一些帮助！
